const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.MoveTo,
		C3.Plugins.Keyboard,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Mouse,
		C3.Plugins.Tilemap,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.MapFunction,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.CallMappedFunction,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Exps.Opacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{fase1_1: 0},
	{Solid: 0},
	{hitbox: 0},
	{Platform: 0},
	{player: 0},
	{dano: 0},
	{fase2_1: 0},
	{faseDH_1: 0},
	{faseMA_1: 0},
	{faseMU_1: 0},
	{faseLE_1: 0},
	{porta: 0},
	{Ativado: 0},
	{Red: 0},
	{Green: 0},
	{Blue: 0},
	{TempValor: 0},
	{Botão: 0},
	{alavanca: 0},
	{faseAN_1: 0},
	{DistanciaLado: 0},
	{DistanciaCima: 0},
	{MoverPara: 0},
	{Sólido: 0},
	{ParedeMovimento: 0},
	{Teclado: 0},
	{fase2_2: 0},
	{fase1_2: 0},
	{faseDH_2: 0},
	{faseLE_2: 0},
	{faseMA_2: 0},
	{faseMU_2: 0},
	{Clone: 0},
	{"8Direction": 0},
	{playerTd: 0},
	{Sine: 0},
	{plataformamovel: 0},
	{faseAN_2: 0},
	{AnguloDeRotacao: 0},
	{AnguloInicial: 0},
	{Girar: 0},
	{PortaRot: 0},
	{preto: 0},
	{luzobjeto: 0},
	{luzplayer: 0},
	{playerTdescuro: 0},
	{Mouse: 0},
	{numerofase: 0},
	{botaofase: 0},
	{Mosaico3: 0},
	{Mosaico: 0},
	{Mosaico2: 0},
	{Sprite: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite8: 0},
	{Sprite12: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite13: 0},
	{Sprite21: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite14: 0},
	{numbers: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{trigger: 0},
	{telafim: 0},
	{Texto: 0},
	{audio: 0},
	{Sprite2: 0},
	{Sprite22: 0},
	{fases_desbloqueadas: 0}
];

self.InstanceType = {
	fase1_1: class extends self.ISpriteInstance {},
	hitbox: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	dano: class extends self.ISpriteInstance {},
	fase2_1: class extends self.ISpriteInstance {},
	faseDH_1: class extends self.ISpriteInstance {},
	faseMA_1: class extends self.ISpriteInstance {},
	faseMU_1: class extends self.ISpriteInstance {},
	faseLE_1: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	alavanca: class extends self.ISpriteInstance {},
	faseAN_1: class extends self.ISpriteInstance {},
	ParedeMovimento: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	fase2_2: class extends self.ISpriteInstance {},
	fase1_2: class extends self.ISpriteInstance {},
	faseDH_2: class extends self.ISpriteInstance {},
	faseLE_2: class extends self.ISpriteInstance {},
	faseMA_2: class extends self.ISpriteInstance {},
	faseMU_2: class extends self.ISpriteInstance {},
	playerTd: class extends self.ISpriteInstance {},
	plataformamovel: class extends self.ISpriteInstance {},
	faseAN_2: class extends self.ISpriteInstance {},
	PortaRot: class extends self.ISpriteInstance {},
	preto: class extends self.ISpriteInstance {},
	luzobjeto: class extends self.ISpriteInstance {},
	luzplayer: class extends self.ISpriteInstance {},
	playerTdescuro: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	botaofase: class extends self.ISpriteInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	numbers: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	trigger: class extends self.ISpriteInstance {},
	telafim: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	audio: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {}
}